server:
  port: 80

swagger:
  enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FPC?serverTimezone=UTC
    username: root
    password: 123456

mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:mapper/*Mapper.xml
  #控制台sql语句打印
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0